name: Flatpak

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update; sudo apt install libgtk-3-dev flatpak flatpak-builder
        flatpak --user remote-add --from flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak --user install -y flathub org.gnome.Platform//3.36 org.gnome.Sdk//3.36
        flatpak --user install -y flathub org.freedesktop.Sdk.Extension.rust-stable//19.08
    - name: Flatpak
      run: make flatpak-development
    - name: Upload Flatpak
      uses: actions/upload-artifact@v2
      with:
        name: flatpak
        path: flatpak-development/repo
