name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt update; sudo apt install libgtk-3-dev libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libsoup2.4-dev libxtst-dev at-spi2-core openbox
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        export DISPLAY=:99.0;
        sh -e /etc/init.d/xvfb start;
        sleep 3 ;
        openbox &;
        cargo test --verbose;
