name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update; sudo apt install libgtk-3-dev flatpak flatpak-builder
        flatpak --user remote-add --from flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak --user install -y flathub org.gnome.Platform//3.36 org.gnome.Sdk//3.36
    - name: Build
      run: cargo build --release
    # - name: DEB
    #   run: make deb
    - name: Flatpak
      run: make flatpak-release; ls flatpak;
    # - name: Upload Artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: deb
    #     path: deb/com.pjtsearch.rptable.deb
