name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt update; sudo apt install libgtk-3-dev
    - name: Build
      run: cargo build --verbose
    - name: DEB
      run: make deb
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: deb
        path: deb/com.pjtsearch.periodic_table.deb
